name: Rust Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-hack
      - name: Build
        run: cargo hack build --feature-powerset
      - name: Run tests
        run: cargo hack test --feature-powerset
      - name: Lint
        run: cargo hack clippy --all-targets --feature-powerset
      - name: Fmt
        run: cargo fmt --all --check
      - name: Build docs
        run: RUSTDOCFLAGS="-D warnings" cargo doc --no-deps
